// All application data in one file
export const appData = {
  careers: [
    {
      id: 1,
      title: "Data Scientist",
      description: "Analyze complex data to help businesses make decisions. Data scientists use statistical methods, machine learning, and analytics to extract insights from data.",
      required_skills: ["Python", "Machine Learning", "Statistics", "SQL", "Data Visualization"],
      salary_range: "₹8-25 LPA",
      growth_outlook: "High demand, 25% growth expected",
      learning_path: ["Statistics Fundamentals", "Python Programming", "Machine Learning", "Deep Learning", "Big Data Tools"],
      growth: "high",
      skill_level: "advanced",
      salary_category: "high",
    },
    {
      id: 2,
      title: "UX Designer",
      description: "Design user-friendly interfaces and experiences. UX designers focus on creating products that provide meaningful and relevant experiences to users.",
      required_skills: ["Figma", "User Research", "Prototyping", "Wireframing", "Design Thinking"],
      salary_range: "₹6-20 LPA",
      growth_outlook: "Growing field, focus on digital experiences",
      learning_path: ["Design Fundamentals", "User Research Methods", "Prototyping Tools", "Interaction Design", "Design Systems"],
      growth: "high",
      skill_level: "intermediate",
      salary_category: "medium",
    },
    {
      id: 3,
      title: "Software Engineer",
      description: "Develop and maintain software applications. Software engineers apply engineering principles to software development.",
      required_skills: ["Programming", "Problem Solving", "System Design", "Database Management", "Testing"],
      salary_range: "₹5-30 LPA",
      growth_outlook: "Excellent prospects across all industries",
      learning_path: ["Programming Basics", "Data Structures", "Web Development", "System Design", "Software Architecture"],
      growth: "high",
      skill_level: "intermediate",
      salary_category: "high",
    },
    {
      id: 4,
      title: "Digital Marketing Specialist",
      description: "Promote brands and products through digital channels. Digital marketers use online platforms to reach customers.",
      required_skills: ["SEO/SEM", "Social Media Marketing", "Content Creation", "Analytics", "Email Marketing"],
      salary_range: "₹4-15 LPA",
      growth_outlook: "Rapid growth with digital transformation",
      learning_path: ["Marketing Fundamentals", "SEO Optimization", "Social Media Strategy", "Content Marketing", "Marketing Analytics"],
      growth: "medium",
      skill_level: "beginner",
      salary_category: "medium",
    },
    {
      id: 5,
      title: "Cloud Architect",
      description: "Design and manage cloud computing strategies. Cloud architects oversee cloud adoption plans and cloud application design.",
      required_skills: ["AWS/Azure", "DevOps", "Security", "Networking", "Architecture Design"],
      salary_range: "₹12-40 LPA",
      growth_outlook: "Extremely high demand with cloud adoption",
      learning_path: ["Cloud Fundamentals", "Platform Certification", "DevOps Tools", "Security Best Practices", "Advanced Architecture"],
      growth: "high",
      skill_level: "advanced",
      salary_category: "high",
    },
    {
      id: 6,
      title: "Data Analyst",
      description: "Interpret data to inform business decisions. Data analysts transform data into insights that drive business value.",
      required_skills: ["Excel", "SQL", "Data Visualization", "Statistics", "Reporting"],
      salary_range: "₹4-18 LPA",
      growth_outlook: "Strong demand across industries",
      learning_path: ["Excel Mastery", "SQL Fundamentals", "Data Visualization Tools", "Statistical Analysis", "Reporting Techniques"],
      growth: "medium",
      skill_level: "beginner",
      salary_category: "medium",
    },
  ],
  
  courses: [
    {
      id: 1,
      title: "Python for Data Science",
      provider: "Coursera",
      description: "Learn Python programming fundamentals for data analysis and visualization.",
      duration: "6 weeks",
      level: "Beginner",
      rating: 4.8,
      features: ["Certificate", "Flexible deadlines", "Peer review"],
    },
    {
      id: 2,
      title: "Machine Learning A-Z™",
      provider: "Udemy",
      description: "Introduction to machine learning algorithms and applications with hands-on Python & R exercises.",
      duration: "8 weeks",
      level: "Intermediate",
      rating: 4.7,
      features: ["Certificate", "Lifetime access", "Practical projects"],
    },
    {
      id: 3,
      title: "Google UX Design Professional Certificate",
      provider: "Coursera",
      description: "Master the fundamentals of user experience design and research to kickstart your UX career.",
      duration: "10 weeks",
      level: "Beginner",
      rating: 4.8,
      features: ["Professional Certificate", "Portfolio projects", "Google certified"],
    },
    {
      id: 4,
      title: "AWS Certified Solutions Architect - Associate",
      provider: "Udemy",
      description: "Learn to deploy and manage applications on Amazon Web Services and pass the certification exam.",
      duration: "12 weeks",
      level: "Intermediate",
      rating: 4.9,
      features: ["Exam prep", "Practice tests", "Expert instructor"],
    },
    {
      id: 5,
      title: "Digital Marketing Fundamentals",
      provider: "Google Digital Garage",
      description: "Master the basics of digital marketing with our free course, packed with practical exercises and real-world examples.",
      duration: "4 weeks",
      level: "Beginner",
      rating: 4.6,
      features: ["Free Certificate", "Self-paced", "Beginner-friendly"],
    },
    {
      id: 6,
      title: "The Complete Full-Stack Web Developer Course",
      provider: "Udemy",
      description: "Learn to build modern web applications using the MERN stack (MongoDB, Express, React, Node.js).",
      duration: "20 weeks",
      level: "Intermediate",
      rating: 4.8,
      features: ["Certificate", "80+ hours of video", "Build 10+ projects"],
    },
  ],
  
  assessmentQuestions: [
    {
      id: 1,
      question: "When faced with a complex problem, what is your initial approach?",
      options: [
        "Break it down into smaller, manageable parts.",
        "Research existing solutions and best practices.",
        "Brainstorm a wide range of creative ideas.",
        "Create a detailed, step-by-step plan before starting.",
        "Experiment with different approaches immediately.",
        "Discuss it with colleagues to get different perspectives.",
        "Analyze the available data to find patterns or insights.",
      ],
    },
    {
      id: 2,
      question: "Which work environment makes you feel most productive?",
      options: [
        "A quiet, focused space for deep concentration.",
        "A highly collaborative, open-plan office.",
        "A flexible, remote environment where I manage my schedule.",
        "A structured, corporate setting with clear processes.",
        "A fast-paced, dynamic startup environment.",
        "A creative studio or workshop with hands-on projects.",
        "An academic or research-oriented setting.",
      ],
    },
    {
      id: 3,
      question: "What kind of tasks give you the most satisfaction?",
      options: [
        "Organizing information and creating efficient systems.",
        "Solving a difficult logical or mathematical puzzle.",
        "Creating something visually beautiful or aesthetic.",
        "Helping or teaching others to understand something.",
        "Persuading or negotiating with people.",
        "Building something tangible with my hands or with code.",
        "Discovering a new insight or pattern from data.",
        "Leading a team and coordinating a project.",
      ],
    },
    {
      id: 4,
      question: "How do you prefer to learn new things?",
      options: [
        "Through structured online courses with clear modules.",
        "By reading books, articles, and documentation.",
        "By watching video tutorials and demonstrations.",
        "Through hands-on projects and learning by doing.",
        "By attending workshops or classes with an instructor.",
        "By discussing concepts with a mentor or expert.",
        "Through self-directed exploration and experimentation.",
      ],
    },
    {
      id: 5,
      question: "In a team project, what role do you naturally take on?",
      options: [
        "The Leader: organizing the team and delegating tasks.",
        "The Analyst: digging into the data and details.",
        "The Innovator: coming up with new and creative ideas.",
        "The Implementer: focusing on getting the work done.",
        "The Mediator: ensuring everyone works together smoothly.",
        "The Specialist: providing deep expertise in an area.",
        "The Presenter: communicating the team's findings.",
      ],
    },
    {
      id: 6,
      question: "Which of these subjects are you most drawn to?",
      options: [
        "Psychology and human behavior.",
        "Technology and computer science.",
        "Art, design, and aesthetics.",
        "Economics and business strategy.",
        "Biology and life sciences.",
        "Mathematics and statistics.",
        "Communication and languages.",
        "Engineering and physics.",
      ],
    },
    {
      id: 7,
      question: "What is your primary motivator at work?",
      options: [
        "Financial reward and stability.",
        "Mastering a new skill and personal growth.",
        "Making a positive impact on society.",
        "Gaining recognition and advancing my career.",
        "Solving intellectually stimulating problems.",
        "Creative expression and innovation.",
        "Having autonomy and control over my work.",
        "Working with a great team and strong social connections.",
      ],
    },
    {
      id: 8,
      question: "How do you handle tight deadlines and pressure?",
      options: [
        "I thrive under pressure; it helps me focus.",
        "I create a detailed to-do list and prioritize.",
        "I communicate with stakeholders to manage expectations.",
        "I focus on one task at a time to avoid being overwhelmed.",
        "I use stress as fuel to get things done.",
        "I ask for help or delegate if possible.",
        "I prefer environments without constant high pressure.",
      ],
    },
    {
      id: 9,
      question: "In a successful project, what part are you most proud of?",
      options: [
        "The flawless execution and efficiency of the process.",
        "The innovative solution no one thought of before.",
        "The positive feedback from users or clients.",
        "The measurable business results achieved.",
        "The complex technical challenge that was overcome.",
        "The strong collaboration that made it happen.",
        "The clean, elegant design and user experience.",
      ],
    },
    {
      id: 10,
      question: "Which statement best describes your long-term career goal?",
      options: [
        "To become a top expert in a specialized field.",
        "To lead a large team or an entire company.",
        "To create my own business or product.",
        "To have a stable, secure job with good work-life balance.",
        "To work on globally impactful projects.",
        "To have the flexibility to work from anywhere.",
        "To constantly learn and adapt to new challenges.",
      ],
    },
  ],
};

export const dummyJobs = [
  { title: "Junior Data Scientist", company: "DataCorp", location: "Bengaluru, India", keywords: ["data scientist", "python", "sql"] },
  { title: "UX/UI Designer", company: "Creative Minds", location: "Remote", keywords: ["ux", "ui", "designer", "figma"] },
  { title: "Backend Software Engineer", company: "CodeBase Inc.", location: "Pune, India", keywords: ["software engineer", "java", "backend"] },
  { title: "Digital Marketing Intern", company: "GrowFast", location: "Mumbai, India", keywords: ["digital marketing", "seo", "intern"] },
  { title: "Senior Cloud Engineer", company: "InfraCloud", location: "Hyderabad, India", keywords: ["cloud", "aws", "senior"] },
];

export const careerQuestions = [
  "1️⃣ Personal Background\n• What's your current education level?\n• Which course/branch/stream are you in?\n• Do you have any work experience or internships? If yes, please describe.",
  "2️⃣ Career Goals & Interests\n• What type of career are you interested in (e.g., software, data science, design, management, research)?\n• Which industries excite you (IT, finance, healthcare, education, gaming, etc.)?\n• Do you prefer working with people, data, machines, or creative tasks?",
  "3️⃣ Skills & Strengths\n• List your technical skills (programming, tools, platforms).\n• What soft skills do you have (communication, teamwork)?\n• Which subjects/topics do you enjoy learning the most?",
  "4️⃣ Learning Preferences\n• How do you prefer to learn (online courses, hands-on projects, books, tutorials)?\n• How much time per week can you dedicate to learning new skills?",
  "5️⃣ Achievements & Portfolio\n• Have you done any projects, competitions, or certifications?\n• Do you have a GitHub, LinkedIn, or portfolio website?",
  "6️⃣ Career Challenges\n• What challenges are you facing in career planning?\n• Are you preparing for any exams or certifications?",
  "7️⃣ Aspirations & Work Style\n• Do you want to work in startups, MNCs, government, or as a freelancer?\n• Are you interested in entrepreneurship?",
  "8️⃣ Location & Flexibility\n• Which locations/countries are you open to?\n• Are you open to remote or only on-site roles?",
  "9️⃣ Timeline & Commitment\n• When do you plan to start your career?\n• Are you looking for internships, full-time roles, or higher studies?",
  "🔟 Feedback & Updates\n• Do you want periodic career tips or skill-building roadmaps?\n• Would you like notifications for events, hackathons, or job openings?",
];

export const chatbotResponses = {
  greetings: "Hiii 👋 I'm your AI Career Mentor! What's your name?",
  farewells: "Goodbye! Best of luck on your career journey.",
  thanks: "You're welcome! I'm happy to help.",
  career_advice: "Let's dive into your career journey! I'll ask a few questions to understand you better.",
  default: "That's a great question! I can guide you on careers, resumes, and interviews.",
};